# Generated by Django 4.2.1 on 2023-07-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(to='main.client', verbose_name='клиент'),
        ),
    ]
